### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by DeeAnie** [BrightBrainsKk/Section-4--Introduction-to-CSS#6]

**Comment by nuranurbekova** [comment]
[section#4 css-selectors.zip](https://github.com/BrightBrainsKk/Section-4--Introduction-to-CSS/files/7001855/section.4.css-selectors.zip)
Сняла видео, написала код. На выполнение ушло 1день.

**Comment by nuranurbekova** [comment]
[section#4 css-selectors.zip](https://github.com/BrightBrainsKk/Section-4--Introduction-to-CSS/files/7001863/section.4.css-selectors.zip)
Сняла видео написала код. На выполнение ушло 1 день.
